import type { RetellVoice } from "@/types/retell";

export const RETELL_VOICE_CATALOG: RetellVoice[] = [
  // Platform Voices (Retell Native)
  {
    voice_id: "retell-Cimo",
    voice_name: "Cimo",
    provider: "retell",
    accent: "American",
    age: "Middle Aged",
    gender: "female",
    avatar_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    trait: "American · Middle Aged · retell",
  },
  {
    voice_id: "retell-Brynne",
    voice_name: "Brynne",
    provider: "retell",
    accent: "American",
    age: "Middle Aged",
    gender: "female",
    avatar_url: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
    preview_audio_url: "https://actions.google.com/sounds/v1/speech/person_2.ogg",
    trait: "American · Middle Aged · retell",
  },
  {
    voice_id: "retell-Chloe",
    voice_name: "Chloe",
    provider: "retell",
    accent: "American",
    age: "Young",
    gender: "female",
    avatar_url: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80",
    preview_audio_url: "https://actions.google.com/sounds/v1/speech/person_3.ogg",
    trait: "American · Young · retell",
  },
  {
    voice_id: "retell-Kate",
    voice_name: "Kate",
    provider: "retell",
    accent: "American",
    age: "Middle Aged",
    gender: "female",
    avatar_url: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80",
    trait: "American · Middle Aged · retell",
  },
  {
    voice_id: "retell-Grace",
    voice_name: "Grace",
    provider: "retell",
    accent: "American",
    age: "Middle Aged",
    gender: "female",
    avatar_url: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    preview_audio_url: "https://actions.google.com/sounds/v1/speech/person_2.ogg",
    trait: "American · Middle Aged · retell",
  },
  {
    voice_id: "retell-Leland",
    voice_name: "Leland",
    provider: "retell",
    accent: "American",
    age: "Young",
    gender: "male",
    avatar_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    preview_audio_url: "https://actions.google.com/sounds/v1/speech/person_4.ogg",
    trait: "American · Young · retell",
  },
  {
    voice_id: "retell-Marissa",
    voice_name: "Marissa",
    provider: "retell",
    accent: "American",
    age: "Middle Aged",
    gender: "female",
    avatar_url: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=150&auto=format&fit=crop&q=80",
    trait: "American · Middle Aged · retell",
  },
  {
    voice_id: "retell-Lily",
    voice_name: "Lily",
    provider: "retell",
    accent: "American",
    age: "Middle Aged",
    gender: "female",
    avatar_url: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=150&auto=format&fit=crop&q=80",
    preview_audio_url: "https://actions.google.com/sounds/v1/speech/person_3.ogg",
    trait: "American · Middle Aged · retell",
  },
  {
    voice_id: "retell-Della",
    voice_name: "Della",
    provider: "retell",
    accent: "American",
    age: "Young",
    gender: "female",
    avatar_url: "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=150&auto=format&fit=crop&q=80",
    preview_audio_url: "https://actions.google.com/sounds/v1/speech/person_2.ogg",
    trait: "American · Young · retell",
  },
  {
    voice_id: "retell-Nico",
    voice_name: "Nico",
    provider: "retell",
    accent: "American",
    age: "Middle Aged",
    gender: "male",
    avatar_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    preview_audio_url: "https://actions.google.com/sounds/v1/speech/person_4.ogg",
    trait: "American · Middle Aged · retell",
  },
  {
    voice_id: "retell-Rita",
    voice_name: "Rita",
    provider: "retell",
    accent: "American",
    age: "Young",
    gender: "female",
    avatar_url: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=150&auto=format&fit=crop&q=80",
    preview_audio_url: "https://actions.google.com/sounds/v1/speech/person_1.ogg",
    trait: "American · Young · retell",
  },
  {
    voice_id: "retell-Merritt",
    voice_name: "Merritt",
    provider: "retell",
    accent: "American",
    age: "Middle Aged",
    gender: "female",
    avatar_url: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    preview_audio_url: "https://actions.google.com/sounds/v1/speech/person_2.ogg",
    trait: "American · Middle Aged · retell",
  },
  {
    voice_id: "retell-Sloane",
    voice_name: "Sloane",
    provider: "retell",
    accent: "American",
    age: "Middle Aged",
    gender: "female",
    avatar_url: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80",
    preview_audio_url: "https://actions.google.com/sounds/v1/speech/person_3.ogg",
    trait: "American · Middle Aged · retell",
  },
  {
    voice_id: "retell-Willa",
    voice_name: "Willa",
    provider: "retell",
    accent: "British",
    age: "Middle Aged",
    gender: "female",
    avatar_url: "https://images.unsplash.com/photo-1534751516642-a171e261452a?w=150&auto=format&fit=crop&q=80",
    preview_audio_url: "https://actions.google.com/sounds/v1/speech/person_1.ogg",
    trait: "British · Middle Aged · retell",
  },
  {
    voice_id: "retell-Maren",
    voice_name: "Maren",
    provider: "retell",
    accent: "British",
    age: "Young",
    gender: "female",
    avatar_url: "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=150&auto=format&fit=crop&q=80",
    preview_audio_url: "https://actions.google.com/sounds/v1/speech/person_2.ogg",
    trait: "British · Young · retell",
  },
  {
    voice_id: "retell-Tamsin",
    voice_name: "Tamsin",
    provider: "retell",
    accent: "American",
    age: "Middle Aged",
    gender: "female",
    avatar_url: "https://images.unsplash.com/photo-1548142813-c348350df52b?w=150&auto=format&fit=crop&q=80",
    preview_audio_url: "https://actions.google.com/sounds/v1/speech/person_3.ogg",
    trait: "American · Middle Aged · retell",
  },
  {
    voice_id: "retell-Ashley",
    voice_name: "Ashley",
    provider: "retell",
    accent: "American",
    age: "Middle Aged",
    gender: "female",
    avatar_url: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=150&auto=format&fit=crop&q=80",
    trait: "American · Middle Aged · retell",
  },
  {
    voice_id: "retell-Andrea",
    voice_name: "Andrea",
    provider: "retell",
    accent: "Mexican",
    age: "Middle Aged",
    gender: "female",
    avatar_url: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    preview_audio_url: "https://actions.google.com/sounds/v1/speech/person_2.ogg",
    trait: "Mexican · Middle Aged · retell",
  },

  // Custom Providers Voices (MiniMax, ElevenLabs, OpenAI, Cartesia, Fish Audio)
  {
    voice_id: "minimax-Adrian",
    voice_name: "Adrian",
    provider: "minimax",
    accent: "American",
    age: "Young",
    gender: "male",
    avatar_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    preview_audio_url: "https://actions.google.com/sounds/v1/speech/person_4.ogg",
    trait: "American · Young · Retell",
  },
  {
    voice_id: "minimax-Andrew",
    voice_name: "Andrew",
    provider: "minimax",
    accent: "American",
    age: "Young",
    gender: "male",
    avatar_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    preview_audio_url: "https://actions.google.com/sounds/v1/speech/person_4.ogg",
    trait: "American · Young · Retell",
  },
  {
    voice_id: "minimax-Ashley",
    voice_name: "Ashley",
    provider: "minimax",
    accent: "American",
    age: "Middle Aged",
    gender: "female",
    avatar_url: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=150&auto=format&fit=crop&q=80",
    preview_audio_url: "https://actions.google.com/sounds/v1/speech/person_1.ogg",
    trait: "American · Middle Aged · Provider",
  },
  {
    voice_id: "minimax-Brynne",
    voice_name: "Brynne",
    provider: "minimax",
    accent: "American",
    age: "Middle Aged",
    gender: "female",
    avatar_url: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
    preview_audio_url: "https://actions.google.com/sounds/v1/speech/person_2.ogg",
    trait: "American · Middle Aged · Retell",
  },
  {
    voice_id: "minimax-Chloe",
    voice_name: "Chloe",
    provider: "minimax",
    accent: "American",
    age: "Young",
    gender: "female",
    avatar_url: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80",
    preview_audio_url: "https://actions.google.com/sounds/v1/speech/person_3.ogg",
    trait: "American · Young · Retell",
  },
  {
    voice_id: "minimax-Cimo",
    voice_name: "Cimo",
    provider: "minimax",
    accent: "American",
    age: "Middle Aged",
    gender: "female",
    avatar_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    preview_audio_url: "https://actions.google.com/sounds/v1/speech/person_1.ogg",
    trait: "American · Middle Aged · Retell",
  },
  {
    voice_id: "minimax-Grace",
    voice_name: "Grace",
    provider: "minimax",
    accent: "American",
    age: "Middle Aged",
    gender: "female",
    avatar_url: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    preview_audio_url: "https://actions.google.com/sounds/v1/speech/person_2.ogg",
    trait: "American · Middle Aged · Retell",
  },
  {
    voice_id: "minimax-Hailey",
    voice_name: "Hailey",
    provider: "minimax",
    accent: "American",
    age: "Young",
    gender: "female",
    avatar_url: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80",
    preview_audio_url: "https://actions.google.com/sounds/v1/speech/person_3.ogg",
    trait: "American · Young · Retell",
  },
  {
    voice_id: "minimax-Nia",
    voice_name: "Nia",
    provider: "minimax",
    accent: "American",
    age: "Young",
    gender: "female",
    avatar_url: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=150&auto=format&fit=crop&q=80",
    preview_audio_url: "https://actions.google.com/sounds/v1/speech/person_1.ogg",
    trait: "American · Young · Retell",
  },

  // ElevenLabs
  {
    voice_id: "11labs-Adrian",
    voice_name: "Adrian",
    provider: "elevenlabs",
    accent: "American",
    age: "Young",
    gender: "male",
    avatar_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    preview_audio_url: "https://actions.google.com/sounds/v1/speech/person_4.ogg",
    trait: "American · Young · ElevenLabs",
  },
  {
    voice_id: "11labs-Rachel",
    voice_name: "Rachel",
    provider: "elevenlabs",
    accent: "American",
    age: "Young",
    gender: "female",
    avatar_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    preview_audio_url: "https://actions.google.com/sounds/v1/speech/person_1.ogg",
    trait: "American · Calm · ElevenLabs",
  },

  // OpenAI
  {
    voice_id: "openai-Alloy",
    voice_name: "Alloy",
    provider: "openai",
    accent: "American",
    age: "Neutral",
    gender: "female",
    avatar_url: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
    preview_audio_url: "https://actions.google.com/sounds/v1/speech/person_2.ogg",
    trait: "American · Neutral · OpenAI",
  },
  {
    voice_id: "openai-Echo",
    voice_name: "Echo",
    provider: "openai",
    accent: "American",
    age: "Middle Aged",
    gender: "male",
    avatar_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    preview_audio_url: "https://actions.google.com/sounds/v1/speech/person_4.ogg",
    trait: "American · Deep · OpenAI",
  },

  // Cartesia
  {
    voice_id: "cartesia-Sonic",
    voice_name: "Sonic",
    provider: "cartesia",
    accent: "American",
    age: "Young",
    gender: "male",
    avatar_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    preview_audio_url: "https://actions.google.com/sounds/v1/speech/person_4.ogg",
    trait: "American · Fast · Cartesia",
  },

  // Fish Audio
  {
    voice_id: "fish-JapaneseMale",
    voice_name: "Kenji",
    provider: "fish_audio",
    accent: "Japanese",
    age: "Middle Aged",
    gender: "male",
    avatar_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    preview_audio_url: "https://actions.google.com/sounds/v1/speech/person_4.ogg",
    trait: "Japanese · Anime · Fish Audio",
  },
];
