const { createClient } = require('@supabase/supabase-js');
const fs = require('fs');
const path = require('path');

// Manually parse .env.local
let supabaseUrl, supabaseServiceKey;
try {
  const envContent = fs.readFileSync(path.join(__dirname, '../.env.local'), 'utf-8');
  envContent.split('\n').forEach(line => {
    const match = line.match(/^\s*([\w.-]+)\s*=\s*(.*)?\s*$/);
    if (match) {
      const key = match[1];
      let value = match[2] || '';
      if (value.startsWith('"') && value.endsWith('"')) {
        value = value.slice(1, -1);
      }
      if (key === 'NEXT_PUBLIC_SUPABASE_URL') supabaseUrl = value.trim();
      if (key === 'SUPABASE_SERVICE_ROLE_KEY') supabaseServiceKey = value.trim();
    }
  });
} catch (e) {
  console.error('Error reading .env.local:', e);
}

if (!supabaseUrl || !supabaseServiceKey) {
  console.error('Missing env vars');
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseServiceKey);

async function run() {
  const activeSubId = '29137520-4de1-47f0-b52d-f702e6ca6929';
  const overageUsage = 849.79; // exceeds 800 total limit by 49.79 minutes

  console.log(`Updating subscription ${activeSubId} minutes_used to ${overageUsage}...`);

  const { data, error } = await supabase
    .from('subscriptions')
    .update({ minutes_used: overageUsage })
    .eq('id', activeSubId)
    .select();

  if (error) {
    console.error('Error updating subscription minutes_used:', error);
    return;
  }

  console.log('Subscription updated successfully:', data);

  // Check if pending invoice was generated by database trigger
  const { data: invoices, error: invError } = await supabase
    .from('pending_overage_invoices')
    .select('*')
    .eq('subscription_id', activeSubId);

  if (invError) {
    console.error('Error fetching generated pending invoice:', invError);
  } else {
    console.log('Generated pending invoices after trigger:', invoices);
  }
}

run();
